"use strict";
/**
 * ChatX 热补丁「落地侧」纯函数（零 Electron / 零 IO，Node 直跑可测）。
 *
 * 与 hotpatch-apply.js 的分工：那边回答「要不要套、套哪一份」，这边回答「怎么落地」
 * ——zip 地址怎么拼、manifest 有没有被动过手脚、退出后替换文件的 helper 怎么调。
 * main.js 只剩 IO（拉取 / 下载 / 校验 / spawn / 退出）。
 *
 * 为什么落地必须交给外部进程：app.asar 与 backend.exe 在本进程运行期间被文件锁
 * 占着，进程内 copy 必失败。helper 先等本进程退出再替换，最后拉起 exe。
 */

/** 64 位小写十六进制才算数：manifest 里 sha256 缺失/畸形 = 校验形同虚设。 */
function isSha256(v) {
  return /^[0-9a-f]{64}$/.test(String(v || "").toLowerCase());
}

/**
 * zip 下载地址 = manifest 同目录下的文件名。
 * **只接受同源**：manifest 已经决定了要装什么文件、以及每个文件的哈希，再让它
 * 自由指定下载主机没有任何收益，却多出一个「指针被改就从别处拉包」的面。
 */
function zipUrlFrom(manifestUrl, zipName) {
  const name = String(zipName || "").trim();
  const base = String(manifestUrl || "").trim();
  if (!name || !base) return "";
  if (name.includes("..") || name.includes("\\") || name.startsWith("/")) return "";
  let u;
  let b;
  try {
    b = new URL(base);
    u = new URL(name, base);
  } catch (e) {
    return "";
  }
  if (u.origin !== b.origin) return "";
  return u.toString();
}

/**
 * manifest 完整性：normalizeManifest 若丢掉了任何一条 files 记录（路径越权 / 重复），
 * 这份 manifest 就不是构建脚本产出的那份。**只套一半的补丁比不套更危险**
 * （app.asar 换了、配套的 shared/inject 没换 = 版本错配的运行时），所以整份拒绝，
 * 而不是「能套多少套多少」。
 */
function manifestTampered(raw, normalized) {
  const rawFiles = raw && Array.isArray(raw.files) ? raw.files.length : 0;
  const kept = normalized && Array.isArray(normalized.files) ? normalized.files.length : 0;
  return rawFiles !== kept;
}

/** manifest 里没有合法 sha256 的文件路径（有一个就不许落地）。 */
function filesMissingHash(normalized) {
  const files = (normalized && Array.isArray(normalized.files) ? normalized.files : []);
  return files.filter((f) => !isSha256(f && f.sha256)).map((f) => (f && f.path) || "");
}

/**
 * staging 内的文件名。zip 名来自远端 manifest → 会变成本地文件名，先做字符白名单
 * （路径分隔符/`..` 全被替换掉，落点永远在 staging 内）。
 * manifest 与 zip **同基名**是刻意的：apply_chatx_hotpatch_node.ps1 缺 -Manifest 时
 * 会按 ChangeExtension 找同名 .json，同名即多一层兜底。
 */
function stagedNames(zipName) {
  const safe = String(zipName || "")
    .replace(/[^A-Za-z0-9._-]/g, "_") // 路径分隔符先没了
    .replace(/\.{2,}/g, "_") // 连点收掉：留着虽已无法穿越，但「看着像穿越」的文件名不该出现
    .replace(/^[._]+/, "") || "hotpatch.zip";
  const base = safe.replace(/\.zip$/i, "");
  return {
    zip: safe,
    manifest: base + ".json",
    runner: "hotpatch-run.ps1",
    script: "apply_chatx_hotpatch_node.ps1",
    log: "hotpatch-apply.log",
    unpacked: "unpacked",
  };
}

/**
 * 退出后落地的 helper 包装脚本。
 *
 * **ASCII-only**：PS 5.1 控制台按 GBK 解码脚本，中文注释会被解成乱码进而语法错误
 * （本仓多次踩过，deploy/desktop/*.ps1 全部同一纪律）。
 *
 * 三件事一件都不能省：
 *   1. 等本壳进程真的退出——asar/backend 运行中被锁，早一秒拷贝就是失败；
 *   2. 调既有 apply_chatx_hotpatch_node.ps1（校验 base/逐文件哈希 + 备份 + 落地 + 拉起）；
 *   3. 全程追加到 staging 日志——失败时这是唯一的第一现场。
 *
 * 参数刻意不叫 $Pid：那是 PowerShell 自动变量，param 里重名直接语法错。
 */
function wrapperScript() {
  return [
    "# ChatX hotpatch runner -- generated by the desktop shell. ASCII only (PS 5.1 GBK).",
    "# Waits for the shell to exit (app.asar is locked while it runs), then applies.",
    "[CmdletBinding()]",
    "param(",
    "  [int]$ShellPid = 0,",
    "  [string]$Script = '',",
    "  [string]$Zip = '',",
    "  [string]$Manifest = '',",
    "  [string]$Log = '',",
    "  [string]$InstallDir = ''",
    ")",
    "$ErrorActionPreference = 'Continue'",
    "function Say($m) {",
    "  $line = '[hotrun] ' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') + ' ' + $m",
    "  if ($Log) { $line | Out-File -FilePath $Log -Append -Encoding utf8 }",
    "}",
    "Say ('wait shell pid=' + $ShellPid)",
    "if ($ShellPid -gt 0) {",
    "  for ($i = 0; $i -lt 240; $i++) {",
    "    if (-not (Get-Process -Id $ShellPid -ErrorAction SilentlyContinue)) { break }",
    "    Start-Sleep -Milliseconds 500",
    "  }",
    "}",
    "Start-Sleep -Milliseconds 1500",
    "Say 'shell gone; applying'",
    "$argv = @('-NoProfile','-ExecutionPolicy','Bypass','-File',$Script,'-Zip',$Zip,'-Manifest',$Manifest,'-Relaunch')",
    "if ($InstallDir) { $argv += @('-InstallDir', $InstallDir) }",
    "& powershell @argv 2>&1 | Out-File -FilePath $Log -Append -Encoding utf8",
    "$code = 0",
    "if ($null -ne $LASTEXITCODE) { $code = $LASTEXITCODE }",
    "Say ('apply exit=' + $code)",
    "exit $code",
  ].join("\r\n") + "\r\n";
}

/** spawn("powershell", …) 的参数表；空 InstallDir 不传（让 helper 走自己的探测）。 */
function wrapperArgs(opts) {
  const o = opts || {};
  const args = [
    "-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden",
    "-File", String(o.runner || ""),
    "-ShellPid", String(Number(o.shellPid) || 0),
    "-Script", String(o.script || ""),
    "-Zip", String(o.zip || ""),
    "-Manifest", String(o.manifest || ""),
    "-Log", String(o.log || ""),
  ];
  if (o.installDir) args.push("-InstallDir", String(o.installDir));
  return args;
}

module.exports = {
  isSha256,
  zipUrlFrom,
  manifestTampered,
  filesMissingHash,
  stagedNames,
  wrapperScript,
  wrapperArgs,
};
