# cs_redeem_bot_service.ps1 — 客服核销 bot 常驻化（计划任务自愈拉活）。
#
# 与 fulfill_trial_service.ps1 的差别：bot 是 Telegram 长轮询**守护进程**（不能
# --once 短跑），故任务模型改为「每 5 分钟检查一次：活着就跳过，死了就拉起」——
# 崩溃自愈同样成立，且绝不会双开（pidfile + 进程存活双判）。
#
# 前置（缺一不可，都是人工一次性动作）：
#   1) @BotFather 建 bot，拿 token；
#   2) 官网 console 建一个 admin 角色的 bot 专用账号；
#   3) 把 scripts\cs_redeem_bot.example.json 抄到下方 -Config 路径并填真值
#      （allowed_user_ids 必须填客服的 Telegram 数字 id，空 = 全拒）。
#
# 用法：
#   scripts\cs_redeem_bot_service.ps1 -Install [-Config D:\chengjie-instances\vendor\cs_redeem_bot.json]
#   scripts\cs_redeem_bot_service.ps1 -Status | -RunNow | -Remove
[CmdletBinding()]
param(
  [switch]$Install,
  [switch]$Remove,
  [switch]$Status,
  [switch]$RunNow,
  [string]$Config = "D:\chengjie-instances\vendor\cs_redeem_bot.json",
  [int]$Every = 5,
  [string]$TaskName = "ChatXCsRedeemBot"
)

$ErrorActionPreference = "Stop"
$Engine = Split-Path -Parent $PSScriptRoot
$LogDir = Join-Path $Engine "logs\cs_redeem_bot"
$Runner = Join-Path $LogDir "_run_cs_redeem_bot.ps1"
$PidFile = Join-Path $LogDir "bot.pid"

function Say($m, $c = "Gray") { Write-Host $m -ForegroundColor $c }
function Head($m) { Write-Host ""; Write-Host $m -ForegroundColor Cyan }

function Write-Runner {
  New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
  # ASCII-only runner：PS5.1 读无 BOM UTF-8 会按 GBK 解码（本仓多次踩过）。
  # python 绝对路径安装期写死：任务以 SYSTEM 跑，按用户装的 Python 不在其 PATH。
  $py = (Get-Command python -ErrorAction SilentlyContinue).Source
  if (-not $py) { throw "找不到 python，无法生成 runner" }
  Say "  python -> $py"
  $body = @"
# generated by cs_redeem_bot_service.ps1 -- do not edit
`$ErrorActionPreference = "Continue"
`$log = Join-Path "$LogDir" ("bot_" + (Get-Date -Format "yyyyMMdd") + ".log")
function W(`$m) { Add-Content -Path `$log -Value ("[" + (Get-Date -Format "HH:mm:ss") + "] " + `$m) -Encoding UTF8 }

# 活着就跳过（pidfile + 进程名双判，防双开）
if (Test-Path "$PidFile") {
  `$oldPid = (Get-Content "$PidFile" -ErrorAction SilentlyContinue | Select-Object -First 1)
  if (`$oldPid) {
    `$p = Get-Process -Id `$oldPid -ErrorAction SilentlyContinue
    if (`$p -and `$p.ProcessName -match "python") { exit 0 }
  }
}
if (-not (Test-Path "$Config")) { W "ERROR config missing: $Config"; exit 2 }
if (-not (Test-Path "$py")) { W "ERROR python missing: $py"; exit 2 }
`$env:PYTHONIOENCODING = "utf-8"
`$proc = Start-Process -FilePath "$py" -WorkingDirectory "$Engine" -WindowStyle Hidden -PassThru ``
  -ArgumentList "scripts\cs_redeem_bot.py","--config","$Config" ``
  -RedirectStandardOutput (Join-Path "$LogDir" "bot.out.log") ``
  -RedirectStandardError (Join-Path "$LogDir" "bot.err.log")
Set-Content -Path "$PidFile" -Value `$proc.Id
W ("started pid=" + `$proc.Id)
Get-ChildItem "$LogDir" -Filter "bot_*.log" -ErrorAction SilentlyContinue |
  Sort-Object Name -Descending | Select-Object -Skip 14 | Remove-Item -Force -ErrorAction SilentlyContinue
exit 0
"@
  [System.IO.File]::WriteAllText($Runner, $body, (New-Object System.Text.ASCIIEncoding))
  Say "  runner -> $Runner"
}

function Protect-Secret([string]$Path) {
  # 配置里有 bot token + console 密码，与厂商密钥同级处理：仅 Administrators/SYSTEM。
  if (-not (Test-Path $Path)) { return }
  try {
    $acl = Get-Acl $Path
    $acl.SetAccessRuleProtection($true, $false)
    $acl.Access | ForEach-Object { [void]$acl.RemoveAccessRule($_) }
    foreach ($who in "BUILTIN\Administrators", "NT AUTHORITY\SYSTEM") {
      $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
        $who, "FullControl", "None", "None", "Allow")))
    }
    Set-Acl -Path $Path -AclObject $acl
    Say ("  已收紧权限（仅 Administrators/SYSTEM）: " + (Split-Path $Path -Leaf))
  } catch {
    Say ("  ! 收紧权限失败（请手工 icacls）: " + (Split-Path $Path -Leaf)) Yellow
  }
}

if ($Install) {
  Head "安装客服核销 bot 常驻任务"
  if (-not (Test-Path $Config)) {
    throw "配置不存在: $Config（抄 scripts\cs_redeem_bot.example.json 并填真值）"
  }
  $cfg = Get-Content $Config -Raw | ConvertFrom-Json
  foreach ($k in "bot_token", "console_user", "console_pass") {
    if (-not $cfg.$k) { throw "配置缺 $k（见 example 注释）" }
  }
  if (-not $cfg.allowed_user_ids -or $cfg.allowed_user_ids.Count -eq 0) {
    throw "allowed_user_ids 为空 = 谁的消息都不处理，先填客服的 Telegram 数字 id"
  }
  Protect-Secret $Config
  Write-Runner
  $tr = "powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$Runner`""
  schtasks /Create /TN $TaskName /TR $tr /SC MINUTE /MO $Every /RU SYSTEM /RL HIGHEST /F | Out-Null
  Say "  已注册 $TaskName（每 $Every 分钟查活拉活，SYSTEM 身份）" Green
  Say "  下一步：-RunNow 立即拉起，然后给 bot 发一条含 BC-XXXX-XXXX 的消息验证" DarkGray
  return
}

if ($Remove) {
  Head "移除客服核销 bot"
  schtasks /Delete /TN $TaskName /F 2>$null | Out-Null
  if (Test-Path $PidFile) {
    $botPid = Get-Content $PidFile -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($botPid) { Stop-Process -Id $botPid -Force -ErrorAction SilentlyContinue }
    Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
  }
  Say "  已移除 $TaskName 并停掉 bot 进程（日志保留）" Green
  return
}

if ($RunNow) {
  Head "立即拉起"
  if (-not (Test-Path $Runner)) { throw "runner 不存在，先 -Install" }
  schtasks /Run /TN $TaskName 2>$null | Out-Null
  Start-Sleep -Seconds 5
  if (Test-Path $PidFile) {
    Say ("  bot pid=" + (Get-Content $PidFile | Select-Object -First 1)) Green
  } else { Say "  还没有 pidfile（看 logs\cs_redeem_bot\bot_*.log）" Yellow }
  return
}

if ($Status) {
  Head "任务"
  $q = schtasks /Query /TN $TaskName /FO LIST /V 2>&1
  if ($LASTEXITCODE -ne 0) { Say "  未安装（-Install 装它）" Yellow }
  else {
    $q | Select-String -Pattern "状态|Status|上次运行时间|Last Run Time|上次结果|Last Result" |
      ForEach-Object { Say ("  " + $_.Line.Trim()) }
  }
  Head "进程"
  $alive = $false
  if (Test-Path $PidFile) {
    $botPid = Get-Content $PidFile -ErrorAction SilentlyContinue | Select-Object -First 1
    $p = if ($botPid) { Get-Process -Id $botPid -ErrorAction SilentlyContinue } else { $null }
    if ($p) { $alive = $true; Say ("  运行中 pid=" + $botPid) Green }
  }
  if (-not $alive) { Say "  未运行（任务下轮会拉起，或 -RunNow）" Yellow }
  Head "日志尾部"
  foreach ($f in "bot.err.log", "bot.out.log") {
    $p = Join-Path $LogDir $f
    if (Test-Path $p) {
      $tail = Get-Content $p -Tail 8 -ErrorAction SilentlyContinue
      if ($tail) { Say "  -- $f"; $tail | ForEach-Object { Say ("  " + $_) } }
    }
  }
  return
}

Say "用法：-Install | -Status | -RunNow | -Remove   （详见脚本头部注释）" Yellow
