# fulfill_trial_service.ps1 — 把试用履约端做成常驻计划任务。
#
# 为什么要常驻：厂商机是签发链上唯一的单点，它不跑，用户点了「免费领取」就永远
# 停在「正在签发」——而且是**静默**的，客户端没报错、官网台账也只是多一条 pending。
# 手工 `python scripts/fulfill_trial.py --interval 60` 挂在某个窗口里，重启即失效。
#
# 为什么用 `--once` + 每 N 分钟触发，而不是常驻守护：
#   守护进程崩了就没人拉它；计划任务每轮新起一个短命进程，崩溃天然自愈，
#   且非零退出会被调度器记下（`-Status` 能看到）。与本仓 watchdog 的既有做法一致。
#
# 密钥不上命令行：`schtasks /Query /V` 会把整条命令打出来，ADMIN_KEY 若写在参数里
# 等于任何能查任务的人都看得到。故任务只调一个 runner 脚本，key 由 runner 运行时
# 从文件读（与厂商私钥同一套处理：只给路径，内容不进任何命令行/日志/台账）。
#
# 用法：
#   # 装（每 5 分钟一轮）
#   scripts\fulfill_trial_service.ps1 -Install -Site https://bd2026.cc `
#       -KeyFile D:\chengjie-instances\vendor\website_admin_key.txt `
#       -Priv D:\chengjie-instances\vendor\chengjie_vendor_private.pem
#   scripts\fulfill_trial_service.ps1 -Status     # 在不在、上次结果、日志尾部
#   scripts\fulfill_trial_service.ps1 -RunNow     # 立刻跑一轮（排障用）
#   scripts\fulfill_trial_service.ps1 -Remove
[CmdletBinding()]
param(
  [switch]$Install,
  [switch]$Remove,
  [switch]$Status,
  [switch]$RunNow,
  [string]$Site = "https://bd2026.cc",
  [string]$KeyFile = "",
  [string]$Priv = "D:\chengjie-instances\vendor\chengjie_vendor_private.pem",
  [int]$Every = 5,
  [string]$TaskName = "ChatXTrialFulfill"
)

$ErrorActionPreference = "Stop"
$Engine = Split-Path -Parent $PSScriptRoot
# 独立目录：`logs\fulfill\` 已被 chatx 订单履约（计划任务 ChatxFulfillWatch）占用，
# 文件名也是 fulfill_yyyyMMdd.log —— 混写会污染它的日志语义，而本脚本的按天轮转
# 更会把它的历史一并删掉（第一版就是这么写的，实测才发现同名撞车）。
$LogDir = Join-Path $Engine "logs\fulfill_trial"
$Runner = Join-Path $LogDir "_run_trial_fulfill.ps1"

function Say($m, $c = "Gray") { Write-Host $m -ForegroundColor $c }
function Head($m) { Write-Host ""; Write-Host $m -ForegroundColor Cyan }

function Write-Runner {
  New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
  # ASCII-only：PS5.1 读无 BOM 的 UTF-8 会按 GBK 解码，中文注释/路径都会走形
  # （本仓 watchdog_emotion_tts.ps1 头上那条教训，装 173 启动脚本时又踩过一次）。
  # 绝对 python 路径在安装期解析并写死：任务以 SYSTEM 身份跑，而本机 Python 是
  # **按用户安装**的（%LOCALAPPDATA%\Programs\Python），SYSTEM 的 PATH 里根本没有它
  # —— 第一版直接写 `python`，结果任务静默跑空、日志只有一行空 exit=（实测抓到）。
  $py = (Get-Command python -ErrorAction SilentlyContinue).Source
  if (-not $py) { throw "找不到 python，无法生成 runner" }
  Say "  python -> $py"
  $body = @"
# generated by fulfill_trial_service.ps1 -- do not edit
`$ErrorActionPreference = "Continue"
`$engine = "$Engine"
`$site   = "$Site"
`$priv   = "$Priv"
`$keyFile = "$KeyFile"
`$py     = "$py"
`$log = Join-Path "$LogDir" ("trial_fulfill_" + (Get-Date -Format "yyyyMMdd") + ".log")
function W(`$m) { Add-Content -Path `$log -Value ("[" + (Get-Date -Format "HH:mm:ss") + "] " + `$m) -Encoding UTF8 }

if (-not (Test-Path `$priv)) { W "ERROR vendor key missing: `$priv"; exit 2 }
`$key = ""
if (`$keyFile -and (Test-Path `$keyFile)) { `$key = (Get-Content `$keyFile -Raw).Trim() }
elseif (`$env:TRIAL_ADMIN_KEY) { `$key = `$env:TRIAL_ADMIN_KEY.Trim() }
if (-not `$key) { W "ERROR admin key not available (KeyFile/TRIAL_ADMIN_KEY)"; exit 2 }

if (-not (Test-Path `$py)) { W "ERROR python missing: `$py"; exit 2 }
`$env:PYTHONIOENCODING = "utf-8"
# python 按 UTF-8 输出，PowerShell 默认按控制台代码页(GBK)解码，再 -Encoding UTF8
# 写回 = 双重编码，日志变乱码（实测所见）。日志的全部价值就是排障时能读，故显式对齐。
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}
`$rc = 99
Push-Location `$engine
try {
  `$out = & `$py scripts\fulfill_trial.py --site `$site --key `$key --priv `$priv --once 2>&1
  if (`$null -ne `$LASTEXITCODE) { `$rc = `$LASTEXITCODE }
} catch { W ("ERROR " + `$_.Exception.Message) } finally { Pop-Location }
# fulfill_trial.py 自己已带 [HH:mm:ss] 前缀，W() 再加一层就是双时间戳，剥掉。
foreach (`$line in `$out) {
  `$s = "`$line".Trim()
  if (`$s) { W (`$s -replace '^\[\d\d:\d\d:\d\d\]\s*', '') }
}
W ("exit=" + `$rc)
# 按天一个文件，保留 14 天。只扫本任务自己的前缀——同目录别放别人的东西，
# 也绝不能像第一版那样用 fulfill_*.log 把 chatx 订单履约的历史一起清掉。
Get-ChildItem "$LogDir" -Filter "trial_fulfill_*.log" -ErrorAction SilentlyContinue |
  Sort-Object Name -Descending | Select-Object -Skip 14 | Remove-Item -Force -ErrorAction SilentlyContinue
exit `$rc
"@
  [System.IO.File]::WriteAllText($Runner, $body, (New-Object System.Text.ASCIIEncoding))
  Say "  runner -> $Runner"
}

function Protect-Secret([string]$Path) {
  <#
    厂商私钥与官网 ADMIN_KEY 是本机最敏感的两件东西：拿到私钥即可**任意伪造授权**，
    比「复用一份已签发的授权」严重一个量级。实测这两个文件继承来的 ACL 让
    BUILTIN\Users 可读、Authenticated Users 可改 —— 任何本机用户都能签license。
    故安装时顺手收紧到 Administrators + SYSTEM（任务以 SYSTEM 跑，必须保留它）。
    靠人记得 icacls 是不可靠的，所以放进安装流程。
  #>
  if (-not (Test-Path $Path)) { return }
  try {
    $acl = Get-Acl $Path
    $acl.SetAccessRuleProtection($true, $false)
    $acl.Access | ForEach-Object { [void]$acl.RemoveAccessRule($_) }
    foreach ($who in "BUILTIN\Administrators", "NT AUTHORITY\SYSTEM") {
      $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
        $who, "FullControl", "None", "None", "Allow")))
    }
    Set-Acl -Path $Path -AclObject $acl
    Say ("  已收紧权限（仅 Administrators/SYSTEM）: " + (Split-Path $Path -Leaf))
  } catch {
    Say ("  ! 收紧权限失败（请手工 icacls）: " + (Split-Path $Path -Leaf)) Yellow
  }
}

if ($Install) {
  Head "安装履约常驻任务"
  if (-not (Test-Path $Priv)) { throw "厂商私钥不存在: $Priv" }
  Protect-Secret $Priv
  if ($KeyFile) { Protect-Secret $KeyFile }
  if (-not $KeyFile) {
    Say "  未给 -KeyFile：runner 将回落读环境变量 TRIAL_ADMIN_KEY" Yellow
    Say "  建议落成文件（任务里不出现明文，也不随会话丢失）" DarkGray
  } elseif (-not (Test-Path $KeyFile)) {
    throw "KeyFile 不存在: $KeyFile"
  }
  Write-Runner
  $tr = "powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$Runner`""
  schtasks /Create /TN $TaskName /TR $tr /SC MINUTE /MO $Every /RU SYSTEM /RL HIGHEST /F | Out-Null
  Say "  已注册 $TaskName（每 $Every 分钟一轮，SYSTEM 身份，不依赖登录会话）" Green
  Say "  站点 $Site" DarkGray
  Say "  下一步：-RunNow 跑一轮确认能取到待办（生产接口没上线时会报 404）" DarkGray
  return
}

if ($Remove) {
  Head "移除履约常驻任务"
  schtasks /Delete /TN $TaskName /F 2>$null | Out-Null
  Say "  已移除 $TaskName（runner 与日志保留）" Green
  return
}

if ($RunNow) {
  Head "立刻跑一轮"
  if (-not (Test-Path $Runner)) { throw "runner 不存在，先 -Install" }
  schtasks /Run /TN $TaskName 2>$null | Out-Null
  Start-Sleep -Seconds 8
  $log = Join-Path $LogDir ("trial_fulfill_" + (Get-Date -Format "yyyyMMdd") + ".log")
  if (Test-Path $log) { Get-Content $log -Tail 15 | ForEach-Object { Say ("  " + $_) } }
  else { Say "  还没有日志（任务可能仍在跑）" Yellow }
  return
}

if ($Status) {
  Head "任务"
  $q = schtasks /Query /TN $TaskName /FO LIST /V 2>&1
  if ($LASTEXITCODE -ne 0) { Say "  未安装（-Install 装它）" Yellow }
  else {
    $q | Select-String -Pattern "状态|Status|上次运行时间|Last Run Time|上次结果|Last Result|下次运行时间|Next Run Time" |
      ForEach-Object { Say ("  " + $_.Line.Trim()) }
    Say "  提示：上次结果 0=正常；非 0 见下方日志（站点不可达/密钥无效都会非 0）" DarkGray
  }
  Head "日志尾部"
  $log = Get-ChildItem $LogDir -Filter "trial_fulfill_*.log" -ErrorAction SilentlyContinue |
    Sort-Object Name -Descending | Select-Object -First 1
  if ($log) { Get-Content $log.FullName -Tail 18 | ForEach-Object { Say ("  " + $_) } }
  else { Say "  无" DarkGray }
  return
}

Say "用法：-Install | -Status | -RunNow | -Remove   （详见脚本头部注释）" Yellow
