/* AUTO-GENERATED by scripts/i18n_desktop_ext.py — 桌面壳渲染层 id overlay。
   勿手改：regen 会覆盖本文件。生成 2026-08-27 04:16 · HY-MT 机翻(占位符掩码) · 0 键。
   装载协议：作为同步 <script> 紧跟 shell-i18n.js 之后（宿主按语言条件装载），经 shellI18n.registerExt
   后装；文件缺失/钩子不在＝静默维持既有回落，绝不影响其他语言坐席。 */
(function (root) {
  'use strict';
  var d = {
  };
  if (root.shellI18n && typeof root.shellI18n.registerExt === 'function') { root.shellI18n.registerExt("id", d); }
  try { if (root.shellI18n && root.shellI18n.lang === "id" && typeof document !== 'undefined') { document.title = root.shellI18n.t('app.title'); } } catch (e) { /* title 刷新失败不阻断 */ }
  if (typeof module !== 'undefined' && module.exports) { module.exports = { lang: "id", dict: d }; }
})(typeof window !== 'undefined' ? window : this);
