/* AUTO-GENERATED by scripts/i18n_desktop_ext.py — 副驾组件 th overlay。
   勿手改：regen 会覆盖本文件。生成 2026-08-27 04:16 · HY-MT 机翻(占位符掩码) · 0 键。
   装载协议：作为同步 <script> 紧跟 cp-i18n.js 之后（宿主按语言条件装载），经 CopilotShared.regExt
   后装；文件缺失/钩子不在＝静默维持既有回落，绝不影响其他语言坐席。 */
(function (root) {
  'use strict';
  var d = {
  };
  if (root.CopilotShared && typeof root.CopilotShared.regExt === 'function') { root.CopilotShared.regExt("th", d); }
  if (typeof module !== 'undefined' && module.exports) { module.exports = { lang: "th", dict: d }; }
})(typeof window !== 'undefined' ? window : this);
