# expose_prod.ps1 - publish the PRODUCTION workspace at https://<slug>.bd2026.cc (default katie).
#
# Idempotent setup/repair tool (safe to re-run any time, e.g. after a VPS deploy clobber):
#   [1] DNS check      : <slug>.bd2026.cc must resolve to the VPS IP (wildcard or host A record)
#   [2] tunnel leg     : VPS 127.0.0.1:<port>/login must answer (ProdTunnel task carries it)
#   [3] LE certificate : certbot webroot via the port-80 catch-all ACME location (skip if live)
#   [4] nginx site     : /etc/nginx/sites-available/prod-<slug>.conf (clone of tenant conf shape:
#                        SSE no-buffer, WS upgrade, 50m media) -> nginx -t gate -> reload
#   [5] end-to-end     : public https probe from THIS machine (the agents' exact path)
#   [6] marker         : .ops\prod_public_url.txt (prod_edge_watchdog picks up the public probe)
#
# ASCII-only on purpose (PowerShell 5.1 decodes BOM-less UTF-8 as GBK).
param(
    [string]$Slug = 'katie',
    [int]$Port = 18799,
    [string]$Key = 'D:\chengjie-instances\.ops\vision_key',
    [string]$VpsIp = '165.154.233.121',
    [string]$VpsUser = 'ubuntu',
    [string]$Domain = 'bd2026.cc'
)
$ErrorActionPreference = 'Stop'
$fqdn = "$Slug.$Domain"
$marker = 'D:\chengjie-instances\.ops\prod_public_url.txt'

function VpsRun([string]$cmd, [int]$timeout = 60) {
    $out = ssh -i $Key -o BatchMode=yes -o StrictHostKeyChecking=accept-new `
        -o ConnectTimeout=$timeout "$VpsUser@$VpsIp" $cmd 2>&1
    return ($out | Out-String).Trim()
}

Write-Host "[1/6] DNS: $fqdn"
$dns = VpsRun "dig +short $fqdn @8.8.8.8 | tail -1"
if ($dns -ne $VpsIp) {
    Write-Host "  FAIL: resolves to '$dns' (want $VpsIp)." -ForegroundColor Red
    Write-Host "  Add DNS at Dynadot: '$Slug' (or wildcard '*') A $VpsIp, then re-run."
    exit 2
}
Write-Host "  ok -> $dns"

Write-Host "[2/6] tunnel leg: VPS 127.0.0.1:$Port"
$leg = VpsRun "curl -s -m 8 -o /dev/null -w '%{http_code}' http://127.0.0.1:$Port/login"
if ($leg -ne '200') {
    Write-Host "  FAIL: VPS loopback :$Port gave '$leg'. Is ProdTunnel running?" -ForegroundColor Red
    Write-Host "  schtasks /Run /TN ProdTunnel   (log: .ops\prod_tunnel.log)"
    exit 3
}
Write-Host "  ok -> 200"

Write-Host "[3/6] certificate"
$hasCert = VpsRun "sudo -n test -d /etc/letsencrypt/live/$fqdn && echo YES || echo NO"
if ($hasCert -ne 'YES') {
    $cb = VpsRun ("sudo -n certbot certonly --webroot -w /var/www/html -d $fqdn " +
                  "--non-interactive --agree-tos --keep-until-expiring 2>&1; echo RC=`$?") 180
    if ($cb -notmatch 'RC=0') {
        Write-Host "  FAIL: certbot:" -ForegroundColor Red
        Write-Host ($cb.Substring([Math]::Max(0, $cb.Length - 600)))
        exit 4
    }
    Write-Host "  issued"
} else {
    Write-Host "  ok (already issued)"
}

Write-Host "[4/6] nginx site prod-$Slug.conf"
$conf = @"
# prod workspace ($Slug) - generated by expose_prod.ps1 (production entrance, NOT a tenant)
# upstream = VPS localhost:$Port <- ssh reverse tunnel (prod_tunnel.ps1 on .117) <- zhiliao
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $fqdn;

    ssl_certificate /etc/letsencrypt/live/$fqdn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$fqdn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50m;

    # reliability P0-4 (2026-08-12): classic scanner probes die at nginx (444),
    # never traverse the ~30KB/s ssh tunnel. Snippet is installed once by hand;
    # keep this include so a re-expose does not silently drop the shield.
    include snippets/scanner-deny.conf;

    location / {
        proxy_pass http://127.0.0.1:$Port;
        proxy_http_version 1.1;
        proxy_set_header Host `$host;
        proxy_set_header X-Real-IP `$remote_addr;
        proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto `$scheme;
        proxy_set_header Upgrade `$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
"@
$b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($conf))
$ng = VpsRun ("echo $b64 | base64 -d | sudo -n tee /etc/nginx/sites-available/prod-$Slug.conf >/dev/null && " +
              "sudo -n ln -sf /etc/nginx/sites-available/prod-$Slug.conf /etc/nginx/sites-enabled/prod-$Slug.conf && " +
              "sudo -n nginx -t 2>&1 && sudo -n systemctl reload nginx && echo NGINX_OK")
if ($ng -notmatch 'NGINX_OK') {
    # nginx -t failed: remove the site so a broken conf never wedges other sites
    VpsRun "sudo -n rm -f /etc/nginx/sites-enabled/prod-$Slug.conf" | Out-Null
    Write-Host "  FAIL (site rolled back):" -ForegroundColor Red
    Write-Host $ng
    exit 5
}
Write-Host "  ok (reloaded)"

Write-Host "[5/6] public end-to-end: https://$fqdn/login"
$code = 0
try {
    $r = Invoke-WebRequest -Uri "https://$fqdn/login" -UseBasicParsing -TimeoutSec 20
    $code = [int]$r.StatusCode
} catch {
    if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
}
if ($code -ne 200) {
    Write-Host "  FAIL: public probe gave $code (VPS edge is up; check from another network / DNS TTL)" -ForegroundColor Red
    exit 6
}
Write-Host "  ok -> 200"

Write-Host "[6/6] marker for prod_edge_watchdog"
"https://$fqdn" | Out-File $marker -Encoding ascii -Force
Write-Host "  wrote $marker"
Write-Host ""
Write-Host "DONE: https://$fqdn/login  (production workspace, protected entrance)" -ForegroundColor Green
exit 0
