# expose_prod.ps1 - publish the PRODUCTION workspace at https://<slug>.bd2026.cc (default katie).
#
# Idempotent setup/repair tool (safe to re-run any time, e.g. after a VPS deploy clobber):
#   [1] DNS check      : <slug>.bd2026.cc must resolve to the VPS IP (wildcard or host A record)
#   [2] tunnel leg     : VPS 127.0.0.1:<port>/login must answer (ProdTunnel task carries it)
#   [3] LE certificate : certbot webroot via the port-80 catch-all ACME location (skip if live)
#   [4] nginx site     : /etc/nginx/sites-available/prod-<slug>.conf (clone of tenant conf shape:
#                        SSE no-buffer, WS upgrade, 50m media) -> nginx -t gate -> reload
#                        Q-14 D (#262, 2026-09-10): own port-80 block (ACME passthrough +
#                        301 to https, no longer riding the yuntech default_server catch-all)
#                        and a 502/503/504 "instance restarting" page (Retry-After 20 +
#                        meta refresh 20; body from prod_restarting.html next to this script).
#                        The previous conf is copied to *.bak_<ts> before tee; a failed
#                        nginx -t restores that copy instead of just unlinking the site.
#   [5] end-to-end     : public https probe from THIS machine (the agents' exact path)
#   [6] marker         : .ops\prod_public_url.txt (prod_edge_watchdog picks up the public probe)
#
# ASCII-only on purpose (PowerShell 5.1 decodes BOM-less UTF-8 as GBK).
param(
    [string]$Slug = 'katie',
    [int]$Port = 18799,
    [string]$Key = 'D:\chengjie-instances\.ops\vision_key',
    [string]$VpsIp = '165.154.233.121',
    [string]$VpsUser = 'ubuntu',
    [string]$Domain = 'bd2026.cc'
)
$ErrorActionPreference = 'Stop'
$fqdn = "$Slug.$Domain"
$marker = 'D:\chengjie-instances\.ops\prod_public_url.txt'

function VpsRun([string]$cmd, [int]$timeout = 60) {
    # -n (StdinNull): one-shot ssh from Windows 9.5p1 can hang forever after a fast remote
    # command when stdin is unattended (Win32-OpenSSH #1334, 2026-09-11); stdin is unused here
    # (the conf/page bodies travel inside $cmd as base64, never via stdin).
    $out = ssh -n -i $Key -o BatchMode=yes -o StrictHostKeyChecking=accept-new `
        -o ConnectTimeout=$timeout "$VpsUser@$VpsIp" $cmd 2>&1
    return ($out | Out-String).Trim()
}

Write-Host "[1/6] DNS: $fqdn"
$dns = VpsRun "dig +short $fqdn @8.8.8.8 | tail -1"
if ($dns -ne $VpsIp) {
    Write-Host "  FAIL: resolves to '$dns' (want $VpsIp)." -ForegroundColor Red
    Write-Host "  Add DNS at Dynadot: '$Slug' (or wildcard '*') A $VpsIp, then re-run."
    exit 2
}
Write-Host "  ok -> $dns"

Write-Host "[2/6] tunnel leg: VPS 127.0.0.1:$Port"
$leg = VpsRun "curl -s -m 8 -o /dev/null -w '%{http_code}' http://127.0.0.1:$Port/login"
if ($leg -ne '200') {
    Write-Host "  FAIL: VPS loopback :$Port gave '$leg'. Is ProdTunnel running?" -ForegroundColor Red
    Write-Host "  schtasks /Run /TN ProdTunnel   (log: .ops\prod_tunnel.log)"
    exit 3
}
Write-Host "  ok -> 200"

Write-Host "[3/6] certificate"
$hasCert = VpsRun "sudo -n test -d /etc/letsencrypt/live/$fqdn && echo YES || echo NO"
if ($hasCert -ne 'YES') {
    $cb = VpsRun ("sudo -n certbot certonly --webroot -w /var/www/html -d $fqdn " +
                  "--non-interactive --agree-tos --keep-until-expiring 2>&1; echo RC=`$?") 180
    if ($cb -notmatch 'RC=0') {
        Write-Host "  FAIL: certbot:" -ForegroundColor Red
        Write-Host ($cb.Substring([Math]::Max(0, $cb.Length - 600)))
        exit 4
    }
    Write-Host "  issued"
} else {
    Write-Host "  ok (already issued)"
}

Write-Host "[4/6] nginx site prod-$Slug.conf"
# Q-14 D-2: the restart-window page lives in /var/www/prod-<slug>/restarting.html (UTF-8 file
# shipped from the repo; this script stays ASCII). Served with the ORIGINAL 5xx status (no "="
# in error_page) so probes/watchdogs still see 502, only humans get a page that retries itself.
$pageDir = "/var/www/prod-$Slug"
$pageSrc = Join-Path $PSScriptRoot 'prod_restarting.html'
if (-not (Test-Path $pageSrc)) {
    Write-Host "  FAIL: $pageSrc missing (restart page source)" -ForegroundColor Red
    exit 5
}
$pageB64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($pageSrc))
$conf = @"
# prod workspace ($Slug) - generated by expose_prod.ps1 (production entrance, NOT a tenant)
# upstream = VPS localhost:$Port <- ssh reverse tunnel (prod_tunnel.ps1 on .117) <- zhiliao

# Q-14 D-1 (#262): explicit port-80 block. Before this, http://$fqdn only redirected because
# the yuntech default_server catch-all happened to; make it this site's own contract.
server {
    listen 80;
    listen [::]:80;
    server_name $fqdn;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
    location / {
        return 301 https://`$host`$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $fqdn;

    ssl_certificate /etc/letsencrypt/live/$fqdn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$fqdn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50m;

    # reliability P0-4 (2026-08-12): classic scanner probes die at nginx (444),
    # never traverse the ~30KB/s ssh tunnel. Snippet is installed once by hand;
    # keep this include so a re-expose does not silently drop the shield.
    include snippets/scanner-deny.conf;

    # Q-14 D-2 (#262): while zhiliao restarts (restart_instance.ps1 window ~20-40s) the
    # tunnel leg is alive but 127.0.0.1:$Port refuses -> nginx 502 (504 on a hung upstream).
    # Serve a self-refreshing page instead of the bare nginx error. Only nginx-generated
    # errors are caught (no proxy_intercept_errors): app-level 5xx JSON stays JSON.
    error_page 502 503 504 /__restarting.html;
    location = /__restarting.html {
        internal;
        root $pageDir;
        try_files /restarting.html =502;
        default_type text/html;
        add_header Retry-After 20 always;
        add_header Cache-Control "no-store" always;
    }

    location / {
        proxy_pass http://127.0.0.1:$Port;
        proxy_http_version 1.1;
        proxy_set_header Host `$host;
        proxy_set_header X-Real-IP `$remote_addr;
        proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto `$scheme;
        proxy_set_header Upgrade `$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}
"@
$b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($conf))
$avail = "/etc/nginx/sites-available/prod-$Slug.conf"
$enabled = "/etc/nginx/sites-enabled/prod-$Slug.conf"
$stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$bak = "$avail.bak_$stamp"
# backup first (cp -a keeps mode/owner); HAD_BAK tells the rollback branch which path to take
$hadBak = VpsRun "if [ -f $avail ]; then sudo -n cp -a $avail $bak && echo HAD_BAK; else echo NO_BAK; fi"
Write-Host "  backup: $hadBak $(if ($hadBak -eq 'HAD_BAK') { $bak })"
$ng = VpsRun ("sudo -n mkdir -p $pageDir && echo $pageB64 | base64 -d | sudo -n tee $pageDir/restarting.html >/dev/null && " +
              "sudo -n chmod 644 $pageDir/restarting.html && " +
              "echo $b64 | base64 -d | sudo -n tee $avail >/dev/null && " +
              "sudo -n ln -sf $avail $enabled && " +
              "sudo -n nginx -t 2>&1 && sudo -n systemctl reload nginx && echo NGINX_OK")
if ($ng -notmatch 'NGINX_OK') {
    # nginx -t failed: put the previous conf back (or unlink the site when there was none)
    # so a broken conf never wedges other sites, then re-run nginx -t to prove the restore.
    if ($hadBak -eq 'HAD_BAK') {
        $rb = VpsRun "sudo -n cp -a $bak $avail && sudo -n nginx -t 2>&1 && echo RESTORE_OK"
    } else {
        $rb = VpsRun "sudo -n rm -f $enabled && sudo -n nginx -t 2>&1 && echo RESTORE_OK"
    }
    Write-Host "  FAIL (nginx -t rejected the new conf; previous state restored: $($rb -match 'RESTORE_OK')):" -ForegroundColor Red
    Write-Host $ng
    exit 5
}
Write-Host "  ok (reloaded)"
Write-Host ("  nginx -t: " + (($ng -split "`n" | Where-Object { $_ -match 'nginx:' }) -join ' | '))
# D-1 check: plain http must 301 to https on the same host+path (Location echoed by curl)
$r80 = VpsRun "curl -s -o /dev/null -m 8 -w '%{http_code} %{redirect_url}' http://$fqdn/workspace/inbox"
Write-Host "  http://$fqdn/workspace/inbox -> $r80"

Write-Host "[5/6] public end-to-end: https://$fqdn/login"
$code = 0
try {
    $r = Invoke-WebRequest -Uri "https://$fqdn/login" -UseBasicParsing -TimeoutSec 20
    $code = [int]$r.StatusCode
} catch {
    if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
}
if ($code -ne 200) {
    Write-Host "  FAIL: public probe gave $code (VPS edge is up; check from another network / DNS TTL)" -ForegroundColor Red
    exit 6
}
Write-Host "  ok -> 200"

Write-Host "[6/6] marker for prod_edge_watchdog"
"https://$fqdn" | Out-File $marker -Encoding ascii -Force
Write-Host "  wrote $marker"
Write-Host ""
Write-Host "DONE: https://$fqdn/login  (production workspace, protected entrance)" -ForegroundColor Green
exit 0
