# scanner-deny.conf - repo SSOT for /etc/nginx/snippets/scanner-deny.conf on the VPS.
# reliability P0-4/P1-9 (2026-08-12): kill classic vulnerability-scanner probes at
# nginx (444 = drop connection, zero bytes) so they never traverse the ssh tunnels
# to the FastAPI backends. Deliberately narrow patterns a FastAPI workspace will
# never legitimately serve; app paths (/login /static /api /workspace ...) untouched.
# Included by: prod-katie.conf (expose_prod.ps1), ai.bd2026.cc, tenant vhosts
# (tenant_lifecycle._nginx_proxy_body; pushed idempotently by tenant_ops expose).
location ~* \.(php|asp|aspx|jsp|cgi|env|bak|sql|rar)$ { access_log off; return 444; }
location ~* ^/(wp-|wordpress|phpmyadmin|pma\b|cgi-bin/|vendor/phpunit|owa/|autodiscover|actuator|solr/|elmah\.axd|dockerfile|docker-compose|\.git|\.env|\.aws|\.ssh|\.vscode|\.idea) { access_log off; return 444; }
