"use client";

import { useState } from "react";
import { useLang } from "./LanguageContext";
import Reveal from "./fx/Reveal";
import { track } from "@/lib/track";
import { LINGOX_WORKBENCH, TOKEN_PACKS, tokenRate } from "@/lib/chatx-pricing";
import { Languages, Loader2, ArrowRight, Sparkles } from "lucide-react";

type Tr = { code: string; native: string; flag: string; text: string };

const COPY = {
  zh: {
    kicker: "智聊 ChatX · 内置拟人翻译",
    head: "实时翻译，亲手试一下",
    sub: "输入任意一句话，AI 实时翻成多国语言——这正是跨境聊天互译时的底层能力。",
    placeholder: "输入中文或任意语言，例如：这个产品多少钱？",
    btn: "实时翻译",
    btnLoading: "翻译中…",
    examples: ["这个产品多少钱？", "我想了解私有部署方案", "Hello, can we talk on WhatsApp?"],
    error: "翻译繁忙，请稍后再试，或点下方联系客服。",
    hint: "演示用途，结果由 AI 实时生成。",
    waiting: "AI 正在翻成多国语言…",
    orderLead: "这个能力现在永久免费",
    orderNote: "标准翻译所有档位免费含、不限字符；专业翻译（术语锁定 / DeepL 认证 / 多模态）按 Token 计量，余额与用量在会员中心随时可查。",
    mergeNote: "🎉 2026-08 新价格：标准翻译永久免费——下载智聊 ChatX 即用，无需购买；原字符包/翻译订阅停售，存量按 150 万字符 = 60,000 Token 免费换发。",
    mergeCta: "下载智聊 ChatX →",
  },
  en: {
    kicker: "ChatX · Built-in Translation",
    head: "Real-time translation — try it yourself",
    sub: "Type any sentence and watch AI translate it into multiple languages live — the same engine behind cross-border chat translation.",
    placeholder: "Type in any language, e.g. How much is this product?",
    btn: "Translate live",
    btnLoading: "Translating…",
    examples: ["How much is this product?", "Tell me about private deployment", "你们支持 USDT 结算吗？"],
    error: "Translation is busy, please retry later or contact us below.",
    hint: "For demo only; results are generated by AI in real time.",
    waiting: "AI is translating into multiple languages…",
    orderLead: "This capability is now free forever",
    orderNote: "Standard translation is free and unlimited in every plan; pro translation (term-lock / certified DeepL / multimodal) meters in tokens — track balance and usage in the membership center.",
    mergeNote: "🎉 New 2026-08 pricing: standard translation is free forever — just download ChatX. Legacy char packs & translate plans are discontinued; unused balances convert at 1.5M chars = 60,000 tokens, free.",
    mergeCta: "Download ChatX →",
  },
} as const;

/** 翻译转化条（2026-08-19 免费化）：免费下载主推 + 专业翻译 Token + 翻译工作台；
 *  价格从 lib/chatx-pricing.ts 单一价格源派生（改价零同步成本）。 */
const LINGOX_ORDER_CHIPS: {
  id: string;
  /** 相对路径（zh 侧；en 由渲染层加 /en 前缀） */
  href: string;
  label: Record<"zh" | "en", string>;
  price: string;
  unit: Record<"zh" | "en", string>;
  hot?: boolean;
}[] = [
  {
    id: "free-download",
    href: "/download/chatx",
    label: { zh: "标准翻译", en: "Standard" },
    price: "$0",
    unit: { zh: "永久免费 · 不限字符", en: "free forever · unlimited" },
    hot: true,
  },
  {
    id: "token-pack-m",
    href: "/order?plan=token-pack-m",
    label: { zh: "专业翻译", en: "Pro translate" },
    price: `${tokenRate("pro_translate").tokens} Token`,
    unit: { zh: "/ 千字符 · Token 包 $" + TOKEN_PACKS[1].price + " 起", en: `/ 1k chars · packs from $${TOKEN_PACKS[1].price}` },
  },
  {
    id: LINGOX_WORKBENCH.key,
    href: `/order?plan=${LINGOX_WORKBENCH.key}`,
    label: { zh: "翻译工作台", en: "Workbench" },
    price: `$${LINGOX_WORKBENCH.monthly}`,
    unit: { zh: "/ 坐席 / 月", en: "/ seat / mo" },
  },
];

/** 可嵌入落地页的翻译面板（首页 section / 通译轨 embed 共用）。 */
export function TranslateDemoPanel({
  where = "home",
  className = "",
}: {
  where?: string;
  className?: string;
}) {
  const { lang } = useLang();
  const c = COPY[lang];
  const [text, setText] = useState("");
  const [busy, setBusy] = useState(false);
  const [res, setRes] = useState<Tr[]>([]);
  const [err, setErr] = useState(false);

  async function callOnce(v: string): Promise<Tr[] | null> {
    try {
      const r = await fetch("/api/translate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: v }),
      });
      const d = await r.json();
      if (d?.ok && Array.isArray(d.translations) && d.translations.length) return d.translations as Tr[];
      return null;
    } catch {
      return null;
    }
  }

  async function run(q: string) {
    const v = q.trim();
    if (!v || busy) return;
    setBusy(true);
    setErr(false);
    setRes([]);
    track("translate_demo", { len: v.length, where });
    let out = await callOnce(v);
    if (!out) {
      await new Promise((r) => setTimeout(r, 700));
      out = await callOnce(v);
    }
    if (out) setRes(out);
    else setErr(true);
    setBusy(false);
  }

  return (
    <div className={`rounded-3xl border border-white/10 bg-white/[0.03] p-5 ${className}`}>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          void run(text);
        }}
        className="flex flex-col gap-3 sm:flex-row"
      >
        <div className="relative flex-1">
          <Languages className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neon-cyan" />
          <input
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder={c.placeholder}
            maxLength={300}
            className="w-full rounded-full border border-white/10 bg-ink-950/60 py-3 pl-9 pr-4 text-sm text-white placeholder:text-slate-500 outline-none focus:border-neon-cyan/50"
          />
        </div>
        <button
          type="submit"
          disabled={busy || !text.trim()}
          className="inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-neon-cyan to-neon-violet px-6 py-3 text-sm font-semibold text-ink-950 transition hover:opacity-90 disabled:opacity-50"
        >
          {busy ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              {c.btnLoading}
            </>
          ) : (
            <>
              {c.btn}
              <ArrowRight className="h-4 w-4" />
            </>
          )}
        </button>
      </form>

      {res.length === 0 && !busy && (
        <div className="mt-3 flex flex-wrap gap-2">
          {c.examples.map((ex) => (
            <button
              key={ex}
              type="button"
              onClick={() => {
                setText(ex);
                void run(ex);
              }}
              className="inline-flex items-center gap-1 rounded-full border border-white/10 bg-white/[0.03] px-3 py-1.5 text-xs text-slate-300 transition hover:border-neon-cyan/40 hover:text-white"
            >
              <Sparkles className="h-3 w-3 text-neon-cyan" />
              {ex}
            </button>
          ))}
        </div>
      )}

      {busy && <p className="mt-4 text-center text-xs text-slate-400">{c.waiting}</p>}
      {err && !busy && <p className="mt-4 text-center text-xs text-amber-300">{c.error}</p>}

      {res.length > 0 && (
        <div className="mt-5 grid gap-2.5 sm:grid-cols-2">
          {res.map((t) => (
            <div
              key={t.code}
              dir={t.code === "ar" ? "rtl" : "ltr"}
              className="rounded-2xl border border-white/10 bg-ink-950/50 p-3.5"
            >
              <div className="mb-1 flex items-center gap-1.5 text-xs font-medium text-neon-cyan">
                <span className="text-sm">{t.flag}</span>
                {t.native}
              </div>
              <p className="text-sm leading-relaxed text-slate-100">{t.text}</p>
            </div>
          ))}
        </div>
      )}

      <p className="mt-4 text-center text-[11px] text-slate-500">{c.hint}</p>
    </div>
  );
}

export default function TranslateDemo() {
  const { lang } = useLang();
  const c = COPY[lang];

  return (
    <section id="translate" className="relative py-24">
      <div className="mx-auto max-w-5xl px-5">
        <Reveal>
          <p className="text-center text-xs font-medium uppercase tracking-[0.28em] text-neon-cyan">{c.kicker}</p>
          <h2 className="mx-auto mt-3 max-w-3xl text-center text-3xl font-bold text-white md:text-4xl">{c.head}</h2>
          <p className="mx-auto mt-4 max-w-2xl text-center text-base text-slate-400">{c.sub}</p>
        </Reveal>
        <Reveal delay={0.05}>
          <div className="mx-auto mt-10 max-w-2xl">
            <TranslateDemoPanel where="home" />
          </div>
        </Reveal>

        {/* 自助下单条：demo 体验 → 直达 /order 深链（通译是主推现金流产品，转化路径必须一跳可达） */}
        <Reveal delay={0.1}>
          <div className="mx-auto mt-10 max-w-2xl text-center">
            <p className="text-xs font-medium uppercase tracking-[0.2em] text-slate-500">{c.orderLead}</p>
            <div className="mt-3 flex flex-wrap items-center justify-center gap-2.5">
              {LINGOX_ORDER_CHIPS.map((chip) => (
                <a
                  key={chip.id}
                  href={`${lang === "zh" ? "" : "/en"}${chip.href}`}
                  onClick={() => track("cta_click", { where: "translate_chips", which: chip.id })}
                  className={`inline-flex items-baseline gap-1.5 rounded-full px-4 py-2 text-sm transition ${
                    chip.hot
                      ? "bg-gradient-to-r from-neon-cyan to-neon-violet font-medium text-ink-950 hover:opacity-90"
                      : "border border-white/15 text-slate-200 hover:border-neon-cyan/50 hover:text-white"
                  }`}
                >
                  {chip.label[lang]}
                  <span className="font-semibold tabular-nums">{chip.price}</span>
                  <span className={`text-xs ${chip.hot ? "text-ink-950/70" : "text-slate-500"}`}>{chip.unit[lang]}</span>
                </a>
              ))}
            </div>
            <p className="mt-3 text-xs text-slate-500">{c.orderNote}</p>
            {/* 通译已并入智聊客户端：合并说明（产品程序层面单一入口） */}
            <p className="mx-auto mt-4 max-w-xl rounded-2xl border border-amber-400/25 bg-amber-400/[0.06] px-4 py-3 text-xs leading-relaxed text-slate-300">
              {c.mergeNote}{" "}
              <a
                href={`${lang === "zh" ? "" : "/en"}/download/chatx`}
                onClick={() => track("cta_click", { where: "translate_merge_note" })}
                className="text-neon-cyan hover:underline"
              >
                {c.mergeCta}
              </a>
            </p>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
