#!/usr/bin/env python3
"""render_download_page.py -- generate the public download page /downloads/fleet/index.html.

The page lives on the VPS at /var/www/dl-mirror/downloads/fleet/index.html (nginx snippet
fleet-downloads.conf). Version, sizes and SHA-256 are computed from the files that are
actually published, so the page can never drift from the binaries. publish_agent.ps1
calls this after copying the versioned files into the mirror.

    python deploy/fleet/render_download_page.py --version 0.3.3 \
        --setup fleet_agent/dist/ChatXAgentSetup.exe --agent fleet_agent/dist/chatx-agent.exe \
        --out index.html

Links always point at the versioned names (ChatXAgentSetup-<ver>.exe, chatx-agent-<ver>.exe):
nginx serves those straight from the mirror, so the hash on the page matches the download.
Stdlib only; runs on Windows (publish machine) and on the VPS (python3).
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import html
import re
import sys
from pathlib import Path
from typing import Dict, Optional

PRODUCT = "智拓群控"
VERSION_RE = re.compile(r"^[0-9][0-9.]*$")  # same shape the nginx location accepts
BASE = "/downloads/fleet"


def file_info(path: Path) -> Dict[str, object]:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return {"sha256": h.hexdigest(), "size": path.stat().st_size}


def human_size(n: int) -> str:
    return f"{n / 1048576:.1f} MB"


def setup_name(version: str) -> str:
    return f"ChatXAgentSetup-{version}.exe"


def agent_name(version: str) -> str:
    return f"chatx-agent-{version}.exe"


def render(version: str, setup: Dict[str, object], agent: Optional[Dict[str, object]] = None,
           date: str = "", base: str = BASE) -> str:
    if not VERSION_RE.match(version or ""):
        raise ValueError(f"bad version: {version!r}")
    for info in (setup, agent):
        if info is not None and not re.fullmatch(r"[0-9a-f]{64}", str(info.get("sha256", ""))):
            raise ValueError("sha256 must be 64 lowercase hex chars")
    e = html.escape
    v = e(version)
    setup_href = f"{base}/{setup_name(version)}"
    date_txt = f"（{e(date)}）" if date else ""
    agent_html = ""
    if agent is not None:
        agent_html = (
            f'<p class="small">单文件版（供升级或技术人员使用）：'
            f'<a href="{base}/{agent_name(version)}">{e(agent_name(version))}</a>'
            f'（{e(human_size(int(agent["size"])))}）<br>SHA256：<code>{e(str(agent["sha256"]))}</code></p>\n'
        )
    return f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<!-- generated by deploy/fleet/render_download_page.py; do not edit by hand -->
<meta name="fleet-download-version" content="{v}">
<title>{PRODUCT} · 节点安装器下载</title>
<style>body{{font-family:system-ui,-apple-system,"Microsoft YaHei",sans-serif;max-width:720px;margin:40px auto;padding:0 20px;color:#222;line-height:1.65}}
h1{{font-size:26px;margin-bottom:4px}}h2{{font-size:18px;margin:26px 0 8px}}.ver{{color:#666;margin-top:0}}
.card{{border:1px solid #ddd;border-radius:12px;padding:18px;margin:16px 0}}
a.btn{{display:inline-block;background:#2563eb;color:#fff;padding:12px 22px;border-radius:8px;text-decoration:none;font-weight:600;font-size:17px}}
code{{font-size:12px;word-break:break-all;color:#555}}ol{{padding-left:22px}}li{{margin:6px 0}}
.small{{font-size:13px;color:#666}}.tip{{border-left:3px solid #f59e0b;background:#fffbeb;padding:10px 14px;border-radius:0 8px 8px 0}}</style></head><body>
<h1>{PRODUCT}</h1><p class="ver">节点安装器 · 当前版本 v{v}{date_txt} · Windows 10 / 11 / Server 2019+（64 位）</p>
<div class="card"><p><a class="btn" href="{e(setup_href)}">下载安装器（{e(setup_name(version))}，{e(human_size(int(setup["size"])))}）</a></p>
<p class="small">SHA256：<code>{e(str(setup["sha256"]))}</code></p></div>
<h2>安装步骤</h2>
<ol>
<li>双击下载的安装器。Windows 询问「是否允许此应用对你的设备进行更改」时点「是」。<strong>安装过程不需要输入任何安装码或注册码。</strong></li>
<li>安装完成页会显示一个<strong>配对码</strong>。把配对码发给管理员，管理员在控制台核对同一个码后点「批准」，这台电脑就上线了。</li>
<li>整间机房批量安装时，管理员会另外发一个「机房安装包」链接。打开后双击其中的 Install.cmd，电脑会直接进入指定分组，不用逐台批准。机房安装包只由管理员私下发放，不在公开页面提供。</li>
</ol>
<h2>被 Windows 拦截时</h2>
<p class="tip">如果出现蓝色窗口「Windows 已保护你的电脑」（SmartScreen）：先点<strong>「更多信息」</strong>，再点<strong>「仍要运行」</strong>。安装器暂未做代码签名，所以会出现这个提示；介意的话可以先核对上面的 SHA256。</p>
{agent_html}<p class="small">产品介绍、重装与安全说明：<a href="/fleet/">bd2026.cc/fleet</a></p>
</body></html>
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=f"render {PRODUCT} download page")
    ap.add_argument("--version", required=True)
    ap.add_argument("--setup", required=True, type=Path, help="installer exe whose hash/size go on the page")
    ap.add_argument("--agent", type=Path, help="single-file chatx-agent exe (optional small link)")
    ap.add_argument("--date", default="", help="release date shown on the page (default: today)")
    ap.add_argument("--out", type=Path, help="write here (default: stdout)")
    a = ap.parse_args(argv)
    date = a.date or _dt.date.today().isoformat()
    page = render(a.version, file_info(a.setup), file_info(a.agent) if a.agent else None, date=date)
    if a.out:
        a.out.write_bytes(page.encode("utf-8"))  # no BOM, LF only
    else:
        sys.stdout.buffer.write(page.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
